server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie-feign

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true

# Feign属性自定义配置，从Spring Cloud Edgware开始支持
feign:
  client:
    config:
      UserFeignClient:
        connectTimeout: 5000 #
        readTimeout: 5000
        # 配置Feign的日志级别，相当于代码配置方式中的Logger
        loggerLevel: full
        # Feign的错误解码器，相当于代码配置方式中的ErrorDecoder
        errorDecoder: com.example.SimpleErrorDecoder
        # 配置重试，相当于代码配置方式中的Retryer
        retryer: com.example.SimpleRetryer
        # 配置拦截器，相当于代码配置方式中的RequestInterceptor
        requestInterceptors:
          - com.example.FooRequestInterceptor
          - com.example.BarRequestInterceptor
        decode404: false
      # 自定义日志级别
      microservice-provider-user:
        loggerLevel: full

logging:
  level:
    com.kuraki.feign.feign.UserFeignClient: debug
